export enum Level {
  DEBUG = 10,
  INFO = 20,
  WARN = 30,
  ERROR = 40,
  FATAL = 50,
}

export enum Layer {
  PRESENTATION = "PRESENTATION",
  GATEWAY = "GATEWAY",
  APPLICATION = "APPLICATION",
  DOMAIN = "DOMAIN",
  PERSISTENCE = "PERSISTENCE",
  INFRA = "INFRA",
  SECURITY = "SECURITY",
  OBSERVABILITY = "OBSERVABILITY",
}
